In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('train.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
dataset.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
finaldata = dataset
y = finaldata.iloc[:,1].values

In [6]:
finaldata.drop(finaldata.columns[[0, 3, 8, 9, 11]],axis=1,inplace=True)
#df.drop(df.columns[[0, 4, 2]], axis = 1, inplace = True) 
finaldata.dropna(inplace=True)

In [7]:
finaldata.head(10)

Survived  Pclass     Sex   Age  SibSp  Parch        Cabin
1          1       1  female  38.0      1      0          C85
3          1       1  female  35.0      1      0         C123
6          0       1    male  54.0      0      0          E46
10         1       3  female   4.0      1      1           G6
11         1       1  female  58.0      0      0         C103
21         1       2    male  34.0      0      0          D56
23         1       1    male  28.0      0      0           A6
27         0       1    male  19.0      3      2  C23 C25 C27
52         1       1  female  49.0      1      0          D33
54         0       1    male  65.0      0      1          B30

In [8]:
for column in ['Sex','SibSp','Parch','Cabin']:

    dummies = pd.get_dummies(finaldata[column])
    finaldata[dummies.columns] = dummies
    finaldata.drop(column,axis=1,inplace=True)

In [9]:
#encoding dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
finaldata.head(20)

Survived  Pclass   Age  female  male  0  1  2  3  4  ...  E68  E77  E8  \
1           1       1  38.0       1     0  1  0  0  0  0  ...    0    0   0   
3           1       1  35.0       1     0  1  0  0  0  0  ...    0    0   0   
6           0       1  54.0       0     1  1  0  0  0  0  ...    0    0   0   
10          1       3   4.0       1     0  0  1  0  0  0  ...    0    0   0   
11          1       1  58.0       1     0  1  0  0  0  0  ...    0    0   0   
21          1       2  34.0       0     1  1  0  0  0  0  ...    0    0   0   
23          1       1  28.0       0     1  1  0  0  0  0  ...    0    0   0   
27          0       1  19.0       0     1  0  0  1  1  0  ...    0    0   0   
52          1       1  49.0       1     0  1  0  0  0  0  ...    0    0   0   
54          0       1  65.0       0     1  0  1  0  0  0  ...    0    0   0   
61          1       1  38.0       1     0  1  0  0  0  0  ...    0    0   0   
62          0       1  45.0       0     1  1  0  0  0  0  ...    0    0   0   
66          1       2  29.0       1     0  1  0  0  0  0  ...    0    0   0   
75          0       3  25.0       0     1  1  0  0  0  0  ...    0    0   0   
88          1       1  23.0       1     0  0  0  1  1  0  ...    0    0   0   
92          0       1  46.0       0     1  1  0  0  0  0  ...    0    0   0   
96          0       1  71.0       0     1  1  0  0  0  0  ...    0    0   0   
97          1       1  23.0       0     1  0  1  0  0  0  ...    0    0   0   
102         0       1  21.0       0     1  0  1  0  0  0  ...    0    0   0   
110         0       1  47.0       0     1  1  0  0  0  0  ...    0    0   0   

     F G63  F G73  F2  F33  F4  G6  T  
1        0      0   0    0   0   0  0  
3        0      0   0    0   0   0  0  
6        0      0   0    0   0   0  0  
10       0      0   0    0   0   1  0  
11       0      0   0    0   0   0  0  
21       0      0   0    0   0   0  0  
23       0      0   0    0   0   0  0  
27       0      0   0    0   0   0  0  
52       0      0   0    0   0   0  0  
54       0      0   0    0   0   0  0  
61       0      0   0    0   0   0  0  
62       0      0   0    0   0   0  0  
66       0      0   0    1   0   0  0  
75       0      1   0    0   0   0  0  
88       0      0   0    0   0   0  0  
92       0      0   0    0   0   0  0  
96       0      0   0    0   0   0  0  
97       0      0   0    0   0   0  0  
102      0      0   0    0   0   0  0  
110      0      0   0    0   0   0  0  

[20 rows x 144 columns]

In [11]:
#missing data (numeric):
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 5:7])
x[:, 5:7] = imputer.transform(x[:, 5:7])
print(x)

[[1 0 3 ... 'A/5 21171' 7.25 nan]
 [2 1 1 ... 'PC 17599' 71.2833 'C85']
 [3 1 3 ... 'STON/O2. 3101282' 7.925 nan]
 ...
 [889 0 3 ... 'W./C. 6607' 23.45 nan]
 [890 1 1 ... '111369' 30.0 'C148']
 [891 0 3 ... '370376' 7.75 nan]]


In [12]:
#missing data (string):
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='constant')
imputer.fit(x[:, 8:-1])
x[:, 8:-1] = imputer.transform(x[:, 8:-1])
print(x)

[[1 0 3 ... 'A/5 21171' 7.25 nan]
 [2 1 1 ... 'PC 17599' 71.2833 'C85']
 [3 1 3 ... 'STON/O2. 3101282' 7.925 nan]
 ...
 [889 0 3 ... 'W./C. 6607' 23.45 nan]
 [890 1 1 ... '111369' 30.0 'C148']
 [891 0 3 ... '370376' 7.75 nan]]


In [13]:
finaldata.head(10)

Survived  Pclass   Age  female  male  0  1  2  3  4  ...  E68  E77  E8  \
1          1       1  38.0       1     0  1  0  0  0  0  ...    0    0   0   
3          1       1  35.0       1     0  1  0  0  0  0  ...    0    0   0   
6          0       1  54.0       0     1  1  0  0  0  0  ...    0    0   0   
10         1       3   4.0       1     0  0  1  0  0  0  ...    0    0   0   
11         1       1  58.0       1     0  1  0  0  0  0  ...    0    0   0   
21         1       2  34.0       0     1  1  0  0  0  0  ...    0    0   0   
23         1       1  28.0       0     1  1  0  0  0  0  ...    0    0   0   
27         0       1  19.0       0     1  0  0  1  1  0  ...    0    0   0   
52         1       1  49.0       1     0  1  0  0  0  0  ...    0    0   0   
54         0       1  65.0       0     1  0  1  0  0  0  ...    0    0   0   

    F G63  F G73  F2  F33  F4  G6  T  
1       0      0   0    0   0   0  0  
3       0      0   0    0   0   0  0  
6       0      0   0    0   0   0  0  
10      0      0   0    0   0   1  0  
11      0      0   0    0   0   0  0  
21      0      0   0    0   0   0  0  
23      0      0   0    0   0   0  0  
27      0      0   0    0   0   0  0  
52      0      0   0    0   0   0  0  
54      0      0   0    0   0   0  0  

[10 rows x 144 columns]

In [14]:
x = finaldata.iloc[:,:].values
y = finaldata.iloc[:,1]

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 42)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
#Logistic Reg

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 42)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=42)

In [19]:
y_pred = classifier.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.values.reshape(len(y_test),1)),1))
#y_pred.values.reshape(-1,1)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[42  0  0]
 [ 3  1  0]
 [ 0  0  1]]


In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9361702127659575

In [22]:
#KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric= 'minkowski', p = 2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [24]:
y_pred = classifier.predict(x_test)
#np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[39  3  0]
 [ 1  3  0]
 [ 0  0  1]]


0.9148936170212766

In [26]:
#SVM

In [27]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [28]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[42  0  0]
 [ 3  1  0]
 [ 0  0  1]]


0.9361702127659575

In [30]:
#Kernel SVM

In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train,y_train)

SVC(random_state=0)

In [32]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[42  0  0]
 [ 3  1  0]
 [ 0  0  1]]


0.9361702127659575

In [34]:
#Naive Bayes

In [35]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [36]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[42  0  0]
 [ 0  4  0]
 [ 0  0  1]]


1.0

In [38]:
#Decision Tree 

In [39]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [40]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[42  0  0]
 [ 0  4  0]
 [ 0  0  1]]


1.0

In [42]:
#Random Forest

In [43]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [44]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[42  0  0]
 [ 0  3  1]
 [ 0  0  1]]


0.9787234042553191

In [46]:
#ANN

In [47]:
ann = tf.keras.models.Sequential()

In [48]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [49]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [50]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [51]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [52]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [53]:
ann.fit(x_train, y_train, validation_data = (x_test, y_test), batch_size = 32, epochs = 300)

Epoch 1/300
5/5 [==============================] - 0s 81ms/step - loss: 1.1518 - accuracy: 0.2754 - val_loss: 0.8409 - val_accuracy: 0.5106
Epoch 2/300
5/5 [==============================] - 0s 10ms/step - loss: 1.0472 - accuracy: 0.3116 - val_loss: 0.7874 - val_accuracy: 0.5319
Epoch 3/300
5/5 [==============================] - 0s 11ms/step - loss: 0.9546 - accuracy: 0.3333 - val_loss: 0.7396 - val_accuracy: 0.5532
Epoch 4/300
5/5 [==============================] - 0s 11ms/step - loss: 0.8739 - accuracy: 0.3768 - val_loss: 0.6976 - val_accuracy: 0.6170
Epoch 5/300
5/5 [==============================] - 0s 9ms/step - loss: 0.8022 - accuracy: 0.4058 - val_loss: 0.6622 - val_accuracy: 0.7021
Epoch 6/300
5/5 [==============================] - 0s 10ms/step - loss: 0.7402 - accuracy: 0.4420 - val_loss: 0.6323 - val_accuracy: 0.7660
Epoch 7/300
5/5 [==============================] - 0s 12ms/step - loss: 0.6827 - accuracy: 0.5072 - val_loss: 0.6045 - val_accuracy: 0.7660
Epoch 8/300
5/5 [====

Epoch 59/300
5/5 [==============================] - 0s 12ms/step - loss: -6.5139 - accuracy: 0.8551 - val_loss: -3.4202 - val_accuracy: 0.8936
Epoch 60/300
5/5 [==============================] - 0s 10ms/step - loss: -6.9681 - accuracy: 0.8551 - val_loss: -3.6726 - val_accuracy: 0.8936
Epoch 61/300
5/5 [==============================] - 0s 11ms/step - loss: -7.4398 - accuracy: 0.8551 - val_loss: -3.9592 - val_accuracy: 0.8936
Epoch 62/300
5/5 [==============================] - 0s 11ms/step - loss: -7.9449 - accuracy: 0.8551 - val_loss: -4.2460 - val_accuracy: 0.8936
Epoch 63/300
5/5 [==============================] - 0s 11ms/step - loss: -8.5083 - accuracy: 0.8551 - val_loss: -4.5210 - val_accuracy: 0.8936
Epoch 64/300
5/5 [==============================] - 0s 13ms/step - loss: -9.0167 - accuracy: 0.8551 - val_loss: -4.8251 - val_accuracy: 0.8936
Epoch 65/300
5/5 [==============================] - 0s 12ms/step - loss: -9.6208 - accuracy: 0.8551 - val_loss: -5.1148 - val_accuracy: 0.8936

5/5 [==============================] - 0s 11ms/step - loss: -101.3397 - accuracy: 0.8551 - val_loss: -56.0763 - val_accuracy: 0.8936
Epoch 116/300
5/5 [==============================] - 0s 12ms/step - loss: -105.1807 - accuracy: 0.8551 - val_loss: -58.2861 - val_accuracy: 0.8936
Epoch 117/300
5/5 [==============================] - 0s 12ms/step - loss: -108.9557 - accuracy: 0.8551 - val_loss: -60.6688 - val_accuracy: 0.8936
Epoch 118/300
5/5 [==============================] - 0s 12ms/step - loss: -113.3577 - accuracy: 0.8551 - val_loss: -63.0707 - val_accuracy: 0.8936
Epoch 119/300
5/5 [==============================] - 0s 13ms/step - loss: -117.4380 - accuracy: 0.8551 - val_loss: -65.6380 - val_accuracy: 0.8936
Epoch 120/300
5/5 [==============================] - 0s 13ms/step - loss: -122.4823 - accuracy: 0.8551 - val_loss: -68.1007 - val_accuracy: 0.8936
Epoch 121/300
5/5 [==============================] - 0s 12ms/step - loss: -127.0657 - accuracy: 0.8551 - val_loss: -70.7366 - val_ac

5/5 [==============================] - 0s 11ms/step - loss: -686.6966 - accuracy: 0.8551 - val_loss: -392.7829 - val_accuracy: 0.8936
Epoch 171/300
5/5 [==============================] - 0s 12ms/step - loss: -706.8575 - accuracy: 0.8551 - val_loss: -404.6039 - val_accuracy: 0.8936
Epoch 172/300
5/5 [==============================] - 0s 13ms/step - loss: -728.2422 - accuracy: 0.8551 - val_loss: -416.2426 - val_accuracy: 0.8936
Epoch 173/300
5/5 [==============================] - 0s 13ms/step - loss: -749.0485 - accuracy: 0.8551 - val_loss: -428.4209 - val_accuracy: 0.8936
Epoch 174/300
5/5 [==============================] - 0s 11ms/step - loss: -770.4348 - accuracy: 0.8551 - val_loss: -441.0002 - val_accuracy: 0.8936
Epoch 175/300
5/5 [==============================] - 0s 13ms/step - loss: -792.7574 - accuracy: 0.8551 - val_loss: -453.9080 - val_accuracy: 0.8936
Epoch 176/300
5/5 [==============================] - 0s 10ms/step - loss: -815.3629 - accuracy: 0.8551 - val_loss: -466.6734 -

5/5 [==============================] - 0s 8ms/step - loss: -2545.9446 - accuracy: 0.8551 - val_loss: -1467.0426 - val_accuracy: 0.8936
Epoch 226/300
5/5 [==============================] - 0s 13ms/step - loss: -2586.6279 - accuracy: 0.8551 - val_loss: -1494.7292 - val_accuracy: 0.8936
Epoch 227/300
5/5 [==============================] - 0s 14ms/step - loss: -2640.7900 - accuracy: 0.8551 - val_loss: -1520.7085 - val_accuracy: 0.8936
Epoch 228/300
5/5 [==============================] - 0s 14ms/step - loss: -2687.4309 - accuracy: 0.8551 - val_loss: -1547.9283 - val_accuracy: 0.8936
Epoch 229/300
5/5 [==============================] - 0s 10ms/step - loss: -2734.4089 - accuracy: 0.8551 - val_loss: -1575.7340 - val_accuracy: 0.8936
Epoch 230/300
5/5 [==============================] - 0s 12ms/step - loss: -2788.1172 - accuracy: 0.8551 - val_loss: -1602.3805 - val_accuracy: 0.8936
Epoch 231/300
5/5 [==============================] - 0s 13ms/step - loss: -2828.2292 - accuracy: 0.8551 - val_loss:

Epoch 280/300
5/5 [==============================] - 0s 12ms/step - loss: -6254.0571 - accuracy: 0.8551 - val_loss: -3618.3186 - val_accuracy: 0.8936
Epoch 281/300
5/5 [==============================] - 0s 13ms/step - loss: -6363.2148 - accuracy: 0.8551 - val_loss: -3674.6948 - val_accuracy: 0.8936
Epoch 282/300
5/5 [==============================] - 0s 12ms/step - loss: -6441.1973 - accuracy: 0.8551 - val_loss: -3738.2212 - val_accuracy: 0.8936
Epoch 283/300
5/5 [==============================] - 0s 11ms/step - loss: -6565.7593 - accuracy: 0.8551 - val_loss: -3792.3762 - val_accuracy: 0.8936
Epoch 284/300
5/5 [==============================] - 0s 12ms/step - loss: -6664.2969 - accuracy: 0.8551 - val_loss: -3847.4421 - val_accuracy: 0.8936
Epoch 285/300
5/5 [==============================] - 0s 12ms/step - loss: -6764.0757 - accuracy: 0.8551 - val_loss: -3911.7161 - val_accuracy: 0.8936
Epoch 286/300
5/5 [==============================] - 0s 12ms/step - loss: -6864.1655 - accuracy: 0.8

In [54]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 3]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[42  0  0]
 [ 4  0  0]
 [ 1  0  0]]


0.8936170212765957